import csv
from datetime import datetime

# =========================================
# INPUT & OUTPUT FILE SETTINGS
# =========================================

# CSV file generated by the PRTG API script
CSV_FILE = "prtg_latest.csv"

# Output HTML report file
HTML_FILE = "prtg_report.html"

# This list will store all rows from the CSV file
rows = []

# =========================================
# READING DATA FROM CSV FILE
# =========================================

# Open the CSV file and read its contents
with open(CSV_FILE, newline='', encoding="utf-8") as file:
    reader = csv.reader(file)

    # Read the first row as table headers
    headers = next(reader)

    # Read all remaining rows as sensor data
    for row in reader:
        rows.append(row)

# Generate current date and time for the report header
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# =========================================
# BUILDING THE HTML REPORT STRUCTURE
# =========================================

html_content = f"""
<html>
<head>
    <title>PRTG Monitoring Report</title>
    <style>
        body {{
            font-family: Arial;
            background-color: #f4f6f9;
            padding: 20px;
        }}
        h1 {{
            color: #333;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background-color: white;
        }}
        th, td {{
            border: 1px solid #ccc;
            padding: 8px;
            text-align: center;
        }}
        th {{
            background-color: #2c3e50;
            color: white;
        }}
        tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}
        .ok {{ background-color: #2ecc71; color: white; }}
        .warning {{ background-color: #f39c12; color: white; }}
        .down {{ background-color: #e74c3c; color: white; }}
    </style>
</head>
<body>

<h1>PRTG Monitoring Report</h1>
<p>Generated at: {now}</p>

<table>
    <tr>
"""

# =========================================
# ADDING TABLE HEADERS TO HTML
# =========================================

for h in headers:
    html_content += f"<th>{h}</th>"

html_content += "</tr>"

# =========================================
# ADDING SENSOR DATA ROWS TO HTML
# =========================================

for row in rows:
    # Sensor status is usually located in column index 3
    status = row[3].lower()

    # Assign color class based on sensor status
    css_class = ""
    if "up" in status:
        css_class = "ok"
    elif "warning" in status:
        css_class = "warning"
    elif "down" in status:
        css_class = "down"

    # Create a new table row with conditional formatting
    html_content += f"<tr class='{css_class}'>"
    for item in row:
        html_content += f"<td>{item}</td>"
    html_content += "</tr>"

# =========================================
# FINAL HTML STRUCTURE
# =========================================

html_content += """
</table>

</body>
</html>
"""

# =========================================
# SAVING FINAL HTML REPORT TO FILE
# =========================================

with open(HTML_FILE, "w", encoding="utf-8") as file:
    file.write(html_content)

print("[+] HTML report generated successfully.")
